# PHP config
#
# VERSION               0.1.0

FROM php:7.1-fpm

RUN apt-get update && apt-get install -y \
        nano \
        curl \
        wget \
        git \
        libpq-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libxslt-dev \
        libicu-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        libbz2-dev \
        cron \
        && pecl channel-update pecl.php.net \
        && pecl install apcu \
        && docker-php-ext-configure pgsql \
        && docker-php-ext-install -j$(nproc) mcrypt zip bz2 mbstring pdo pdo_pgsql pcntl \
        && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
        && docker-php-ext-install -j$(nproc) gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini
COPY www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000